import Link from "next/link"
import './globals.css'
import LoginBtn from "./LoginBtn"
import {getServerSession} from "next-auth"
import {authOptions} from "@/pages/api/auth/[...nextauth]"

export const metadata = {
  title: 'Welcome to jimin-log',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link className="navbar-left" style={{color: 'Grey', fontSize: '30px' }} href="/">👻 Welcome!
            </Link>
          <Link className="navbar-right" style={{fontSize: '30px' }} href="/write">📝</Link>
          <LoginBtn></LoginBtn>
        </div>
        
        {children}
      </body>
    </html>
  )
}
